challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  verification_endpoint: "http://challenge_server:8000/api/v1/verify"
  framework_images:
    - name: seleniumbase
      image: redteamsubnet61/seleniumbase@sha256:617c872e14364c1eaf84c0583b7b4f250d8d93846eed1a8c1d5d5cdfdf42802a
    - name: seleniumdriverless
      image: redteamsubnet61/seleniumdriverless@sha256:afdb31623f6b3db47262ef35e59e713447c0693a736133ec85d29b0ee6337739
    - name: patchright
      image: redteamsubnet61/patchright@sha256:df1d11fb3f806b6a69fd064c4281b52584b28f7b28d224569bf76f8f9b12db98
    - name: nodriver
      image: redteamsubnet61/nodriver@sha256:65675845c8e63c311d80af5271616d55b821ad0e114d8c73958d0f449137c8ca
    - name: puppeteerextra
      image: redteamsubnet61/puppeteerextra@sha256:cd603dcd06d205ff311e682bbca06b1719e4521adeff65b766ce64bc7bc13ab2
    - name: zendriver
      image: redteamsubnet61/zendriver@sha256:5c5b81b94b46d6fa77cee7570ca5285c1046dfb0bcca53a6c80d2eb0fb2dec53
    - name: camoufox
      image: redteamsubnet61/camoufox@sha256:4703f30c759771cb67b4d0e498af5ec0533c6086c153f489a76a6583aca556aa
    - name: botasaurus
      image: redteamsubnet61/botasaurus@sha256:f6c96cd91d8ef985aaa53e77a44eb8f154cd3ed4e00327240595e56d9d3d2aba
    - name: pydoll
      image: redteamsubnet61/pydoll@sha256:c30ce0be424a6364a3725e4ec037d01791df274a0a96ed05d273be0a816df279
